export interface Page<T> { items: T[]; total: number; page: number; pageSize: number }
export interface Branch { id: string; code: string; name: string; timezone: string; isSample: boolean }
export interface Me { id: string; displayName: string; role: string; phone: string; staffNo: string | null; branchId: string | null; organisation: { id: string; name: string } }
export interface Person { id: string; displayName: string; role: string; phone: string; staffNo: string | null; status: string; branchId: string | null; branch: string | null }
export interface Guard {
  id: string; guardNo: string; fullName: string; branchId: string; branch: string | null; phone: string | null; nationalId: string | null; psraRegNo: string | null; psraExpiry: string | null;
  nssfNo: string | null; shaNo: string | null; kraPin: string | null; restWeekday: number | null; hiredOn: string; exitedOn: string | null; status: string; hasPin: boolean; isSample: boolean;
  monthlyBasicCents?: number; allowanceCents?: number;
}
export interface Client { id: string; name: string; contactName: string | null; contactPhone: string | null; contactEmail: string | null; kraPin: string | null; paymentTermsDays: number; status: string; hasPortal: boolean; sites: number }
export interface Site { id: string; clientId: string; client: string; branchId: string; branch: string; name: string; address: string | null; lat: number | null; lng: number | null; geofenceM: number | null; checkpointsOrdered: boolean; roundsPerShift: number; active: boolean; checkpoints: number; posts?: PostRow[] }
export interface PostRow { id: string; siteId: string; name: string; guardsRequired: number; active: boolean }
export interface Checkpoint { id: string; name: string; seq: number; active: boolean; token?: string }
export interface Rate { id: string; postId: string | null; post: string | null; basis: "per_shift" | "per_hour"; amountCents: number; effectiveFrom: string }
export interface Template { id: string; name: string; startTime: string; endTime: string; active: boolean; minutes: number }
export interface Shift { id: string; branchId: string; siteId: string; site: string; client: string; postId: string; post: string; guardId: string | null; guard: string | null; guardNo: string | null; startAt: string; endAt: string; scheduledMinutes: number; status: string; published: boolean; overtimeApprovedMinutes: number; overtimeNote: string | null; day: string }
export interface AttEvent { id: number; kind: string; at: string; effectiveAt: string; method: string; geofence: string; distanceM: number | null; accuracyM: number | null; reason: string | null; by: string | null }
export interface BoardRow { shiftId: string; siteId: string; site: string; client: string; post: string; guardId: string | null; guard: string | null; guardNo: string | null; startAt: string; endAt: string; state: string; late: boolean; lateMinutes: number; inAt: string | null; outAt: string | null; inOverridden: boolean; outOverridden: boolean; geofence: string | null; method: string | null }
export interface Board { day: string; counts: Record<string, number>; items: BoardRow[]; total: number; page: number; pageSize: number }
export interface Swap { id: string; shiftId: string; status: string; reason: string | null; decisionNote: string | null; createdAt: string; requestedBy: string | null; decidedBy: string | null; fromGuard: string; toGuard: string; startAt: string; endAt: string; site: string; post: string }
export interface Patrol { rounds: { index: number; complete: boolean; outOfOrder: boolean; startedAt: string; visited: string[]; missed: string[] }[]; completeRounds: number; roundsRequired: number; shortfall: number; checkpoints: number; scans: number; outsideGeofence: number }
export interface PatrolDay { shiftId: string; site: string; post: string; guard: string | null; roundsRequired: number; completeRounds: number; shortfall: number; outsideGeofence: number }
export interface Incident { id: string; incidentNo: string; siteId: string; site: string; client: string; shiftId: string | null; guardId: string | null; guard: string | null; severity: string; category: string; narrative: string; occurredAt: string; createdAt: string; reportedBy: string | null; status: string; notes?: { id: number; kind: string; body: string; at: string; by: string | null }[] }
export interface Settings {
  minWageCents: number; allowancesCountTowardMin: boolean; standardMonthlyHours: number; overtimeMultiplierBp: number; restDayMultiplierBp: number; holidayMultiplierBp: number; checkinEarlyMinutes: number;
  lateGraceMinutes: number; missedAfterMinutes: number; defaultGeofenceM: number; maxHoursPerWeek: number | null; minRestHours: number | null; billBasis: "scheduled" | "actual";
}
export interface SettingsView { organisation: { isDemo: boolean; name: string; psraLicenceNo: string | null }; settings: Settings; permissions: string[]; capabilities: { billingMode: string } }
export interface Overview {
  day: string; attendance: Record<string, number>; openIncidents: Record<string, number>; pendingSwaps: number; openShiftsNextWeek: number; unbilledShifts?: number; minimumWageCents?: number;
  payroll?: { month: string; guards: number; grossCents: number; netCents: number; employerCostCents: number; belowMinimum: number; blocking: number; warnings: number; tables: { ready: boolean; missing: string[] }; unresolvedShifts: number };
  debtors?: { totalCents: number; overdueCents: number; clients: number };
}
export interface Onboarding { isSample: boolean; items: { key: string; title: string; done: boolean; hint: string }[]; doneCount: number; total: number }
export interface Billing { mode: "mock" | "live"; status: string; writesAllowed: boolean; trialEndsAt: string; coveredUntil: string; suspendsAt: string; daysLeft: number; billingRef: string; billedUnits: number; quote: { planCode: string; unitCount: number; unitCents: number; amountCents: number }; creditCents: number; outstandingCents: number; pay: { shortcode: string; accountNumber: string; amountCents: number } | null; invoices: { id: string; number: string; periodStart: string; periodEnd: string; unitCount: number; amountCents: number; paidCents: number; status: string; issuedAt: string }[] }
export interface RateTable { kind: "nssf" | "sha" | "housing" | "paye"; config: Record<string, unknown>; source: string; status: string; confirmedAt: string | null; confirmedBy: string | null; note: string | null }
export interface Period { id: string; month: string; status: string; openedAt: string; closedAt: string | null; closedBy: string | null; payslips?: number; grossCents?: number; netCents?: number; snapshot?: { acknowledged?: string | null } }
export interface Flag { code: string; severity: "block" | "warn"; message: string }
export interface Payslip { id: string; guardId: string; guardNo: string; guardName: string; nationalId: string | null; daysInMonth: number; daysEmployed: number; basicCents: number; allowanceCents: number; premiumCents: number; overtimeCents: number; adjustmentsCents: number; grossCents: number; deductions: { kind: string; label: string; employeeCents: number; employerCents: number; applied: boolean }[]; employeeDeductionsCents: number; netCents: number; employerCostCents: number; minRequiredCents: number; belowMinimum: boolean; flags: Flag[] }
export interface Compliance { month: string; closed: boolean; minimumWageCents: number; allowancesCountTowardMin: boolean; guards: number; belowMinimum: { guardId: string; guardNo: string; guardName: string; basicCents: number; requiredCents: number; shortfallCents: number; daysEmployed: number }[]; flagCounts: Record<string, number>; unresolvedShifts: number; deductionTables: { kind: string; status: string; source: string }[]; firmPsraLicenceRecorded: boolean; notice: string }
export interface RunResult { period: Period; summary: { guards: number; grossCents: number; netCents: number; employerCostCents: number; deductionsCents: number; belowMinimum: number; blocking: number; warnings: number }; unresolvedShifts: number; tables: { ready: boolean; missing: string[] } }
export interface Adjustment { id: string; guard: string; guardNo: string; effectiveMonth: string; amountCents: number; kind: string; reason: string; relatedMonth: string | null; by: string | null; createdAt: string }
export interface InvoiceRow { id: string; number: string; clientId: string; client: string; month: string; issueDate: string; dueDate: string; totalCents: number; creditedCents: number; paidCents: number; balanceCents: number; status: string; verifiedShifts: number; unverifiedShifts: number; disputed: boolean }
export interface InvoiceDetail extends InvoiceRow { lines: { id: string; description: string; basis: string; quantity: number; unitCents: number; amountCents: number }[]; creditNotes: { id: string; number: string; amountCents: number; reason: string; createdAt: string; by: string | null }[]; events: { id: number; kind: string; body: string; at: string; by: string | null }[]; payments: { id: string; amountCents: number; method: string; reference: string | null; receivedOn: string }[] }
export interface Evidence { shiftId: string; site: string; post: string; guard: string | null; guardNo: string | null; startAt: string; endAt: string; inAt: string | null; outAt: string | null; inOverridden: boolean; outOverridden: boolean; geofence: string | null; verifiedMinutes: number; billedCents: number }
export interface InvoicePreview { month: string; totalCents: number; billedShifts: number; notVerified: number; noRate: number; lines: { description: string; basis: string; quantity: number; unitCents: number; amountCents: number }[] }
export interface Debtors { asOf: string; buckets: string[]; totals: Record<string, number>; totalCents: number; items: { clientId: string; client: string; buckets: Record<string, number>; totalCents: number; invoices: number; oldestDaysOverdue: number }[] }
export interface PaymentRow { id: string; clientId: string; client: string; amountCents: number; receivedOn: string; method: string; reference: string | null; onAccountCents: number }
export interface Margin { month: string; costKnown: boolean; costNote: string | null; totals: { netCents: number; costCents: number; marginCents: number }; items: { clientId: string; client: string; invoicedCents: number; creditedCents: number; netCents: number; costCents: number; marginCents: number; marginPercent: number | null }[] }
export interface Portal { client: string; month: string; sites: { site: string; totals: { scheduled: number; verified: number; late: number; missed: number }; days: { day: string; scheduled: number; verified: number; late: number; missed: number }[] }[]; notice: string }
export interface Holiday { day: string; name: string }
export interface AuditRow { id: number; actor: string | null; action: string; entity: string; entityId: string | null; detail: Record<string, unknown>; at: string }
export interface PostPick { id: string; name: string; siteId: string; site: string; client: string }
