CREATE TABLE suppliers (
id PRIMARY KEY,
company_name VARCHAR(255) NOT NULL,
contact_email VARCHAR (255) UNIQUE NOT NULL, 
county VARCHAR(100) NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);