// Screenshot sets copied from each project's own screenshots/ directory.
// Regenerate by re-running the copy step rather than editing by hand.
export interface Shot {
  src: string;
  caption: string;
}

export const galleries: Record<string, Shot[]> = {
  "sifa": [
    { src: "/shots/sifa/01-overview.jpg", caption: "Overview" },
    { src: "/shots/sifa/02-feed-explorer.jpg", caption: "Feed explorer" },
    { src: "/shots/sifa/03-vector-search.jpg", caption: "Vector search" },
    { src: "/shots/sifa/04-ranker.jpg", caption: "Ranker" },
    { src: "/shots/sifa/05-registry.jpg", caption: "Registry" },
    { src: "/shots/sifa/06-experiment.jpg", caption: "Experiment" },
    { src: "/shots/sifa/07-drift-stable.jpg", caption: "Drift" },
    { src: "/shots/sifa/08-load-test.jpg", caption: "Load test" },
  ],
  "aegis": [
    { src: "/shots/aegis/01-login.jpg", caption: "Login" },
    { src: "/shots/aegis/02-overview.jpg", caption: "Overview" },
    { src: "/shots/aegis/03-runs.jpg", caption: "Runs" },
    { src: "/shots/aegis/04-run-detail-approval-gate.jpg", caption: "Run detail approval gate" },
    { src: "/shots/aegis/05-workflows.jpg", caption: "Workflows" },
    { src: "/shots/aegis/06-screening-form.jpg", caption: "Screening" },
    { src: "/shots/aegis/08-retention-model.jpg", caption: "Retention model" },
    { src: "/shots/aegis/09-compliance.jpg", caption: "Compliance" },
    { src: "/shots/aegis/11-audit-trail.jpg", caption: "Audit trail" },
  ],
  "smartseason": [
    { src: "/shots/smartseason/01-login.jpg", caption: "Login" },
    { src: "/shots/smartseason/02-overview.jpg", caption: "Overview" },
    { src: "/shots/smartseason/03-farms.jpg", caption: "Farms" },
    { src: "/shots/smartseason/04-seasons.jpg", caption: "Seasons" },
    { src: "/shots/smartseason/05-workers.jpg", caption: "Workers" },
    { src: "/shots/smartseason/06-tasks.jpg", caption: "Tasks" },
    { src: "/shots/smartseason/08-fraud-cases.jpg", caption: "Fraud cases" },
    { src: "/shots/smartseason/09-live.jpg", caption: "Live" },
    { src: "/shots/smartseason/10-team.jpg", caption: "Team" },
    { src: "/shots/smartseason/11-advisor.jpg", caption: "Advisor" },
  ],
  "smartre": [
    { src: "/shots/smartre/01-home.jpg", caption: "Home" },
    { src: "/shots/smartre/02-properties.jpg", caption: "Properties" },
    { src: "/shots/smartre/03-property-detail.jpg", caption: "Property detail" },
    { src: "/shots/smartre/04-login.jpg", caption: "Login" },
    { src: "/shots/smartre/10-admin-command-center.jpg", caption: "Admin command center" },
    { src: "/shots/smartre/11-admin-verification-queue.jpg", caption: "Admin verification queue" },
    { src: "/shots/smartre/12-admin-revenue.jpg", caption: "Admin revenue" },
    { src: "/shots/smartre/13-admin-users.jpg", caption: "Admin users" },
    { src: "/shots/smartre/20-landlord-dashboard.jpg", caption: "Landlord dashboard" },
    { src: "/shots/smartre/21-landlord-rent-roll.jpg", caption: "Landlord rent roll" },
    { src: "/shots/smartre/22-landlord-maintenance.jpg", caption: "Landlord maintenance" },
    { src: "/shots/smartre/30-seller-dashboard.jpg", caption: "Seller dashboard" },
    { src: "/shots/smartre/31-seller-listings.jpg", caption: "Seller listings" },
    { src: "/shots/smartre/32-seller-verification.jpg", caption: "Seller verification" },
    { src: "/shots/smartre/40-buyer-dashboard.jpg", caption: "Buyer dashboard" },
    { src: "/shots/smartre/41-buyer-viewings.jpg", caption: "Buyer viewings" },
    { src: "/shots/smartre/42-buyer-payments.jpg", caption: "Buyer payments" },
    { src: "/shots/smartre/50-tenant-tenancy.jpg", caption: "Tenant tenancy" },
  ],
  "forecourt": [
    { src: "/shots/forecourt/00-landing.jpg", caption: "Landing page" },
    { src: "/shots/forecourt/00b-pricing.jpg", caption: "Pricing" },
    { src: "/shots/forecourt/01-login.jpg", caption: "Login" },
    { src: "/shots/forecourt/02-overview.jpg", caption: "Overview" },
    { src: "/shots/forecourt/03-flags.jpg", caption: "Flags" },
    { src: "/shots/forecourt/04-jobs.jpg", caption: "Jobs" },
    { src: "/shots/forecourt/05-payments.jpg", caption: "Payments" },
    { src: "/shots/forecourt/06-water-telemetry.jpg", caption: "Water telemetry" },
    { src: "/shots/forecourt/07-sites.jpg", caption: "Sites" },
    { src: "/shots/forecourt/08-daily-report.jpg", caption: "Daily report" },
    { src: "/shots/forecourt/09-flag-detail.jpg", caption: "Flag detail" },
  ],
  "soko": [
    { src: "/shots/soko/01-sign-in.jpg", caption: "Sign in" },
    { src: "/shots/soko/02-overview.jpg", caption: "Overview" },
    { src: "/shots/soko/03-orders.jpg", caption: "Orders" },
    { src: "/shots/soko/04-order-routing.jpg", caption: "Order routing" },
    { src: "/shots/soko/05-printable-receipt.jpg", caption: "Printable receipt" },
    { src: "/shots/soko/06-catalogue.jpg", caption: "Catalogue" },
    { src: "/shots/soko/07-suppliers.jpg", caption: "Suppliers" },
    { src: "/shots/soko/08-offers.jpg", caption: "Offers" },
    { src: "/shots/soko/09-wastage.jpg", caption: "Wastage" },
    { src: "/shots/soko/10-billing.jpg", caption: "Billing" },
    { src: "/shots/soko/11-supplier-orders.jpg", caption: "Supplier orders" },
    { src: "/shots/soko/12-supplier-pricing.jpg", caption: "Supplier pricing" },
    { src: "/shots/soko/13-storefront.jpg", caption: "Storefront" },
    { src: "/shots/soko/14-customer-orders.jpg", caption: "Customer orders" },
  ],
  "church-cms": [
    { src: "/shots/church-cms/01-login.jpg", caption: "Login" },
    { src: "/shots/church-cms/02-dashboard.jpg", caption: "Dashboard" },
    { src: "/shots/church-cms/03-members.jpg", caption: "Members" },
    { src: "/shots/church-cms/04-gifts.jpg", caption: "Gifts" },
    { src: "/shots/church-cms/05-roles.jpg", caption: "Roles" },
    { src: "/shots/church-cms/07-events.jpg", caption: "Events" },
    { src: "/shots/church-cms/09-dashboard-light.jpg", caption: "Dashboard light" },
    { src: "/shots/church-cms/10-journal.jpg", caption: "Journal" },
    { src: "/shots/church-cms/11-income-statement.jpg", caption: "Income statement" },
    { src: "/shots/church-cms/12-bills.jpg", caption: "Bills" },
    { src: "/shots/church-cms/13-gift-receipt.jpg", caption: "Gift receipt" },
  ],
  "mara": [
    { src: "/shots/mara/01-catalogue.jpg", caption: "Catalogue" },
    { src: "/shots/mara/02-sale-tab.jpg", caption: "Sale tab" },
    { src: "/shots/mara/03-take-payment.jpg", caption: "Take payment" },
    { src: "/shots/mara/04-receipt.jpg", caption: "Receipt" },
    { src: "/shots/mara/05-journal-server-copy.jpg", caption: "Journal server copy" },
    { src: "/shots/mara/06-summary.jpg", caption: "Summary" },
  ],
  "hms": [
    { src: "/shots/hms/01-overview.jpg", caption: "Overview" },
    { src: "/shots/hms/02-queue.jpg", caption: "Queue" },
    { src: "/shots/hms/03-patients.jpg", caption: "Patients" },
    { src: "/shots/hms/04-patient-chart.jpg", caption: "Patient chart" },
    { src: "/shots/hms/05-encounter.jpg", caption: "Encounter" },
    { src: "/shots/hms/06-laboratory.jpg", caption: "Laboratory" },
    { src: "/shots/hms/07-lab-critical-result.jpg", caption: "Lab critical result" },
    { src: "/shots/hms/09-billing.jpg", caption: "Billing" },
    { src: "/shots/hms/10-invoice.jpg", caption: "Invoice" },
    { src: "/shots/hms/11-claims-readiness.jpg", caption: "Claims readiness" },
    { src: "/shots/hms/12-claim-detail.jpg", caption: "Claim detail" },
    { src: "/shots/hms/13-wards.jpg", caption: "Wards" },
    { src: "/shots/hms/14-reports.jpg", caption: "Reports" },
    { src: "/shots/hms/15-audit.jpg", caption: "Audit" },
    { src: "/shots/hms/16-roles.jpg", caption: "Roles" },
  ],
};
