export interface Product { id: string; name: string; genericName: string | null; strength: string | null; form: string | null; packSize: string | null; gtin: string | null; category: "otc" | "prescription" | "controlled"; unit: string; reorderLevel: number; listPriceCents: number; active: boolean }
export interface Branch { id: string; code: string; name: string; tillNumber: string | null; timezone: string; isSample: boolean }
export interface StockRow { productId: string; name: string; strength: string | null; form: string | null; category: string; reorderLevel: number; listPriceCents: number; inDate: number; expired: number; nextExpiry: string | null }
export interface Batch { id: string; productId: string; product: string; category: string; batchNo: string; expiryDate: string; qtyOnHand: number; qtyReceived: number; unitCostCents: number }
export interface AlertBatch { batchId: string; product: string; batchNo: string; expiryDate: string; daysToExpiry: number; qty: number; valueCents: number }
export interface Alerts { expired: AlertBatch[]; expiring: AlertBatch[]; lowStock: { productId: string; product: string; reorderLevel: number; inDate: number }[]; warningDays: number }
export interface SaleRow { id: string; number: string; day: string; status: string; totalCents: number; paidCents: number; cashier: string; createdAt: string }
export interface SaleDetail { id: string; number: string; branchId: string; day: string; status: string; cashier: string; customer: string | null; subtotalCents: number; discountCents: number; totalCents: number; paidCents: number; dueCents: number; voidReason: string | null; createdAt: string; lines: { id: string; productId: string; name: string; category: string; qty: number; unitPriceCents: number; lineTotalCents: number; returnedQty: number }[]; payments: { method: string; amountCents: number; externalRef: string | null; receivedAt: string }[] }
export interface DispensingRow { id: string; dispensedAt: string; saleNumber: string; product: string; category: string; qty: number; batches: string | null; patientName: string; patientPhone: string | null; patientAgeYears: number | null; patientSex: string | null; prescriberName: string; prescriberRegNo: string | null; prescriptionRef: string | null; directions: string | null; dispensedBy: string; licenceNo: string | null; witness: string | null }
export interface Register { balances: { product_id: string; product: string; balance: number }[]; entries: { id: number; product: string; kind: string; qty_delta: number; balance_after: number; batch_no: string | null; patient_name: string | null; prescriber: string | null; reason: string | null; created_at: string; actor: string; witness: string }[] }
export interface Supplier { id: string; name: string; phone: string | null; active: boolean }
export interface Customer { id: string; name: string; phone: string | null; creditLimitCents: number; priceListId: string | null; balanceCents: number }
export interface Payables { items: { id: string; supplier: string; invoiceNumber: string; invoiceDate: string; dueDate: string | null; totalCents: number; paidCents: number; balanceCents: number; overdue: boolean }[]; outstandingCents: number; overdueCents: number }
export interface Stocktake { status: string; id?: string; note?: string | null; startedAt?: string; lines?: { batchId: string; product: string; category: string; batchNo: string; expiryDate: string; expectedQty: number; countedQty: number | null; variance: number | null; varianceValueCents: number | null }[] }
export interface ClosePreview { day: string; closed: boolean; salesCount: number; voidsCount: number; expectedCashCents: number; mpesaCents: number; creditCents: number; pendingCents: number; cashiers: { cashierId: string; name: string; takenCents: number; refundedCents: number; expectedCashCents: number }[] }
export interface CloseRow { id: string; day: string; salesCount: number; expectedCashCents: number; countedCashCents: number; cashVarianceCents: number; mpesaCents: number; creditCents: number; pendingCents: number; closedAt: string; closedBy: string }
export interface Billing { mode: "mock" | "live"; status: string; writesAllowed: boolean; trialEndsAt: string; coveredUntil: string; suspendsAt: string; daysLeft: number; billingRef: string; billedBranches: number; quote: { planCode: string; branchCount: number; unitCents: number; amountCents: number }; creditCents: number; outstandingCents: number; pay: { shortcode: string; accountNumber: string; amountCents: number } | null; invoices: { id: string; number: string; periodStart: string; periodEnd: string; branchCount: number; amountCents: number; paidCents: number; status: string; issuedAt: string }[] }
export interface Onboarding { items: { key: string; title: string; done: boolean; hint: string }[]; doneCount: number; total: number; sampleDataVisible: boolean }
export interface NttsStatus { integrated: boolean; adapter: string; pendingEvents: number; oldestPending: string | null; notice: string }
export interface NttsEvent { id: number; eventType: string; gtin: string | null; batchNo: string | null; expiryDate: string | null; serial: string | null; qty: number; occurredAt: string }
export interface Person { id: string; displayName: string; role: string; phone: string; licenceNo: string | null; status: string; branchId: string | null; branch: string | null }
export interface Me { id: string; displayName: string; role: string; phone: string; licenceNo: string | null; branchId: string | null; organisation: { id: string; name: string } }
export interface ScanResult { scan: { format: string; gtin: string | null; batchNo: string | null; expiryDate: string | null; serial: string | null }; product: Product | null; inDate: number; serialStatus: "in_stock" | "sold" | "unknown" | null }
